name: Lint

on: pull_request

jobs:
  code:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16.13.0

      - name: Install dependencies
        uses: Jaid/action-npm-install@v1.2.4
        with:
          packageManager: "yarn"

      - name: Run ESLint
        run: yarn lint
